
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class AccesoBD extends javax.swing.JFrame
{
    DefaultTableModel m;
    Connection conexion;
    Statement sentencia;
    boolean correcto = true;
    /**
     * Creates new form AccesoBD
     */
    public AccesoBD() {
        initComponents();
        PrepararBaseDatos();
        prepararTabla();
        mostrarTrabajadores();
    }
    
    void prepararTabla()
    {
        String titulos[] = new String[4];
        
        m = new DefaultTableModel(null, titulos);
        tabla.setModel(m);
    }
    
    void PrepararBaseDatos()
    {
    
        
        try
        {
            //1.- Cargar el controlador
            String controlador="com.mysql.jdbc.Driver";
            Class.forName(controlador).newInstance();
            
            //2.- Crear el objeto conexión.
            String DBURL="jdbc:mysql://localhost/manempsa";
            String usuario="root";
            String password="";
            
            conexion = DriverManager.getConnection(DBURL,usuario,password);
            
            //3.- Crear el objeto sentencia.
            sentencia = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido conectar a la base de datos, comprueba que esté activa (activar XAMP)", "Error al iniciar la aplicación", WIDTH, null);
            correcto = false;
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error al cargar el controlador.");
            correcto = false;
        }     
    }
    
    void mostrarTrabajadores()
    {
        try
        {
            String fecha;
            String titulos[] = {"DNI", "Nombre", "Apellidos", "Sueldo", "Fecha", "Matrícula"};
            m = new DefaultTableModel(null, titulos);
            
            ResultSet r = sentencia.executeQuery("select * from trabajadores");
            
            String fila[] = new String[6];
            
            while(r.next())
            {
                fila[0] = r.getString("DNI");
                fila[1] = r.getString("Nombre");
                fila[2] = r.getString("Apellido");
                fila[3] = r.getString("Sueldo").replace(".", ",");
                fecha = r.getString("Fecha");
                fecha = fecha.substring(8, 10) + "/" + fecha.substring(5, 7) + "/" + fecha.substring(0, 4);
                fila[4] = fecha;
                fila[5] = r.getString("Matricula");
                
                m.addRow(fila);
            }
            
            tabla.setModel(m);
            tabla.setAutoResizeMode(AUTO_RESIZE_ALL_COLUMNS);
            
            hacerCalculos(r);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al extraer los datos de la tabla " + e);
        }
    }
    
    void hacerCalculos(ResultSet r)
    {
        int ntrab = 0;
        double ssueldo = 0;
        double media;
        
        try
        {
            r.beforeFirst();
            
            while(r.next())
            {
                ntrab++;
                ssueldo = ssueldo + r.getDouble("sueldo");
            }
            
            media = ssueldo / ntrab;
            
            txtNtrab.setText(String.valueOf(ntrab));
            txtSmedio.setText(String.valueOf(media));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al realizar cálculos " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAddTrabajador = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNSueldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNDia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNMatricula = new javax.swing.JTextField();
        txtNMes = new javax.swing.JTextField();
        txtNAnio = new javax.swing.JTextField();
        btnNAceptar = new javax.swing.JButton();
        btnNCancelar = new javax.swing.JButton();
        dModTrabajador = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMDni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMApellidos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMSueldo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMDia = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMMatricula = new javax.swing.JTextField();
        txtMMes = new javax.swing.JTextField();
        txtMAnio = new javax.swing.JTextField();
        btnMAceptar = new javax.swing.JButton();
        btnMCancelar = new javax.swing.JButton();
        dFilTrabajador = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFDni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFApellidos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFSueldo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFDia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtFMatricula = new javax.swing.JTextField();
        txtFMes = new javax.swing.JTextField();
        txtFAnio = new javax.swing.JTextField();
        btnFAceptar = new javax.swing.JButton();
        btnFCancelar = new javax.swing.JButton();
        cSueldo = new javax.swing.JComboBox();
        cFecha = new javax.swing.JComboBox();
        btnFVer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbOrden = new javax.swing.JComboBox();
        rbAsc = new javax.swing.JRadioButton();
        rbDesc = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtNtrab = new javax.swing.JTextField();
        txtSmedio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Añadir nuevo trabajador");

        jLabel2.setText("DNI:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Sueldo:");

        jLabel6.setText("Fecha:");

        jLabel7.setText("Matricula:");

        btnNAceptar.setText("Aceptar");
        btnNAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAceptarActionPerformed(evt);
            }
        });

        btnNCancelar.setText("Cancelar");
        btnNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dAddTrabajadorLayout = new javax.swing.GroupLayout(dAddTrabajador.getContentPane());
        dAddTrabajador.getContentPane().setLayout(dAddTrabajadorLayout);
        dAddTrabajadorLayout.setHorizontalGroup(
            dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtNMatricula))
                        .addComponent(jLabel3)
                        .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                            .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                                            .addComponent(txtNDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(48, 48, 48)
                            .addComponent(txtNDni, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                        .addComponent(btnNAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNCancelar))
                    .addComponent(jLabel1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dAddTrabajadorLayout.setVerticalGroup(
            dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAddTrabajadorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNAceptar)
                    .addComponent(btnNCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Modificar trabajador");

        jLabel9.setText("DNI:");

        txtMDni.setEditable(false);

        jLabel10.setText("Nombre:");

        jLabel11.setText("Apellidos:");

        jLabel12.setText("Sueldo:");

        jLabel13.setText("Fecha:");

        jLabel14.setText("Matricula:");

        btnMAceptar.setText("Aceptar");
        btnMAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAceptarActionPerformed(evt);
            }
        });

        btnMCancelar.setText("Cancelar");
        btnMCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dModTrabajadorLayout = new javax.swing.GroupLayout(dModTrabajador.getContentPane());
        dModTrabajador.getContentPane().setLayout(dModTrabajadorLayout);
        dModTrabajadorLayout.setHorizontalGroup(
            dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dModTrabajadorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(dModTrabajadorLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(txtMMatricula))
                        .addComponent(jLabel10)
                        .addGroup(dModTrabajadorLayout.createSequentialGroup()
                            .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dModTrabajadorLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dModTrabajadorLayout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(dModTrabajadorLayout.createSequentialGroup()
                                            .addComponent(txtMDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dModTrabajadorLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(48, 48, 48)
                            .addComponent(txtMDni, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dModTrabajadorLayout.createSequentialGroup()
                        .addComponent(btnMAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMCancelar))
                    .addComponent(jLabel8))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dModTrabajadorLayout.setVerticalGroup(
            dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dModTrabajadorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dModTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMAceptar)
                    .addComponent(btnMCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setText("Filtrar trabajadores");

        jLabel16.setText("DNI:");

        jLabel17.setText("Nombre:");

        jLabel18.setText("Apellidos:");

        jLabel19.setText("Sueldo:");

        jLabel20.setText("Fecha:");

        jLabel21.setText("Matricula:");

        btnFAceptar.setText("Aceptar");
        btnFAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAceptarActionPerformed(evt);
            }
        });

        btnFCancelar.setText("Cancelar");
        btnFCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCancelarActionPerformed(evt);
            }
        });

        cSueldo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));

        cFecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));

        btnFVer.setText("Ver todos");
        btnFVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFVerActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenación"));

        cbOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Sin ordenación)", "DNI", "Nombre", "Apellidos", "Sueldo", "Fecha", "Matrícula" }));

        buttonGroup1.add(rbAsc);
        rbAsc.setSelected(true);
        rbAsc.setText("ASC");

        buttonGroup1.add(rbDesc);
        rbDesc.setText("DESC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAsc)
                    .addComponent(rbDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rbAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDesc)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dFilTrabajadorLayout = new javax.swing.GroupLayout(dFilTrabajador.getContentPane());
        dFilTrabajador.getContentPane().setLayout(dFilTrabajadorLayout);
        dFilTrabajadorLayout.setHorizontalGroup(
            dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                        .addComponent(btnFAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFCancelar))
                    .addComponent(jLabel17)
                    .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(48, 48, 48)
                        .addComponent(txtFDni))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtFMatricula))
                    .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                        .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                                .addComponent(cFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                                .addComponent(cSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFApellidos)))
                    .addComponent(txtFNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        dFilTrabajadorLayout.setVerticalGroup(
            dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dFilTrabajadorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtFDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dFilTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFAceptar)
                    .addComponent(btnFCancelar)
                    .addComponent(btnFVer))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Acciones"));

        btnEliminar.setText("Eliminar Trabajador");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAdd.setText("Añadir Trabajador");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Trabajador");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAdd)
                    .addComponent(btnModificar)
                    .addComponent(btnFiltrar))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jLabel22.setText("Nº Trabajadores:");

        jLabel23.setText("Sueldo Medio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNtrab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtSmedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtNtrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try
        {
            conexion.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "No se puede cerrar la base de datos");
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(!correcto)
        {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila, resp;
        String dni;
        
        try
        {
            fila = tabla.getSelectedRow();
            
            if(fila == -1)
            {
                JOptionPane.showMessageDialog(rootPane, "Selecciona el trabajador a eliminar");
            }
            else
            {
                resp = JOptionPane.showConfirmDialog(rootPane, "¿Eliminar el trabajador seleccionado?", "Eliminar", JOptionPane.YES_NO_OPTION);
                
                if(resp == JOptionPane.YES_OPTION)
                {
                    m = (DefaultTableModel)tabla.getModel();
                    dni = (String) m.getValueAt(fila, 0);
                    
                    sentencia.executeUpdate("delete from trabajadores where dni = '" + dni + "'");
                    mostrarTrabajadores();
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar el trabajador");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        dAddTrabajador.setSize(300, 400);
        dAddTrabajador.setModal(true);
        dAddTrabajador.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCancelarActionPerformed
        dAddTrabajador.dispose();
    }//GEN-LAST:event_btnNCancelarActionPerformed

    private void btnNAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAceptarActionPerformed
        String consulta = "";
        
        try
        {
            consulta += "insert into trabajadores values (";
            consulta += "'" + txtNDni.getText() + "',";
            consulta += "'" + txtNNombre.getText() + "',";
            consulta += "'" + txtNApellidos.getText() + "',";
            consulta += txtNSueldo.getText() + ",";
            consulta += "'" + txtNAnio.getText() + "-" + txtNMes.getText() + "-" + txtNDia.getText() + "',";
            consulta += "'" + txtNMatricula.getText() + "')";
            
            sentencia.executeUpdate(consulta);
            
            dAddTrabajador.dispose();
            mostrarTrabajadores();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al introducir el nuevo trabajador " + e);
        }
    }//GEN-LAST:event_btnNAceptarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila;
        String dni, nom, ape, sueldo, fecha, mat;
        
        fila = tabla.getSelectedRow();
        
        if(fila == -1)
        {
            JOptionPane.showMessageDialog(rootPane, "Selecciona el trabajador a modificar");
        }
        else
        {
            m = (DefaultTableModel) tabla.getModel();
            
            dni = (String) m.getValueAt(fila, 0);
            nom = (String) m.getValueAt(fila, 1);
            ape = (String) m.getValueAt(fila, 2);
            sueldo = (String) m.getValueAt(fila, 3);
            fecha = (String) m.getValueAt(fila, 4);
            mat = (String) m.getValueAt(fila, 5);
            
            txtMDni.setText(dni);
            txtMNombre.setText(nom);
            txtMApellidos.setText(ape);
            txtMSueldo.setText(sueldo);
            txtMDia.setText(fecha.substring(0, 2));
            txtMMes.setText(fecha.substring(3, 5));
            txtMAnio.setText(fecha.substring(6, 10));
            txtMMatricula.setText(mat);
            
            dModTrabajador.setSize(300, 400);
            dModTrabajador.setModal(true);
            dModTrabajador.setVisible(true);
            mostrarTrabajadores();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAceptarActionPerformed
        String consulta = "";
        
        try
        {
            consulta += "update trabajadores set ";
            consulta += "nombre = '" + txtMNombre.getText() + "',";
            consulta += "apellido = '" + txtMApellidos.getText() + "',";
            consulta += "sueldo = " + txtMSueldo.getText() + ",";
            consulta += "fecha = '" + txtMAnio.getText() + "-" + txtMMes.getText() + "-" + txtMDia.getText() + "',";
            consulta += "matricula = '" + txtMMatricula.getText() + "'";
            consulta += " where dni = '" + txtMDni.getText() + "'";
            
            sentencia.executeUpdate(consulta);
            
            dModTrabajador.dispose();
            mostrarTrabajadores();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al modificar el trabajador " + e);
        }
    }//GEN-LAST:event_btnMAceptarActionPerformed

    private void btnMCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCancelarActionPerformed
        dModTrabajador.dispose();
    }//GEN-LAST:event_btnMCancelarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        dFilTrabajador.setSize(300, 500);
        dFilTrabajador.setModal(true);
        dFilTrabajador.setVisible(true);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnFAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAceptarActionPerformed
        String dni, nom, ape, sueldo, fecha, mat, cbSueldo, cbFecha, orden, consulta;
        int ncond = 0;
        
        dni = txtFDni.getText();
        nom = txtFNombre.getText();
        ape = txtFApellidos.getText();
        sueldo = txtFSueldo.getText().replace(",", ".");
        fecha = txtFAnio.getText() + "/" + txtFMes.getText() + "/" + txtFDia.getText();
        mat = txtFMatricula.getText();
        cbSueldo = (String) cSueldo.getSelectedItem();
        cbFecha = (String) cFecha.getSelectedItem();
        orden = (String) cbOrden.getSelectedItem();
        
        consulta = "select * from trabajadores ";
        
        if(! dni.equals(""))
        {
            ncond++;
            consulta += "where dni like '%" + dni + "%' ";
        }
        
        if(! nom.equals(""))
        {
            ncond++;
            if(ncond == 1)
            {
                consulta += "where nombre like '%" + nom + "%' ";
            }
            else
            {
                consulta += "and nombre like '%" + nom + "%' ";
            }
        }
        
        if(! ape.equals(""))
        {
            ncond++;
            if(ncond == 1)
            {
                consulta += "where apellido like '%" + ape + "%' ";
            }
            else
            {
                consulta += "and apellido like '%" + ape + "%' ";
            }
        }
        
        if(! sueldo.equals(""))
        {
            ncond++;
            if(ncond == 1)
            {
                consulta += "where sueldo " + cbSueldo + sueldo;
            }
            else
            {
                consulta += "and sueldo " + cbSueldo + sueldo;
            }
        }
        
        if(! fecha.equals("//"))
        {
            ncond++;
            if(ncond == 1)
            {
                consulta += "where fecha " + cbFecha + fecha;
            }
            else
            {
                consulta += "and fecha " + cbFecha + fecha;
            }
        }
        
        if(! mat.equals(""))
        {
            ncond++;
            if(ncond == 1)
            {
                consulta += "where matricula like '%" + mat + "%' ";
            }
            else
            {
                consulta += "and matricula like '%" + mat + "%' ";
            }
        }
        
        if(! orden.equals("(Sin ordenación"))
        {
            if(rbAsc.isSelected())
            {
                consulta += "order by " + orden + " " + rbAsc.getText();
            }
            else
            {
                consulta += "order by " + orden + " " + rbDesc.getText();
            }
        }
        
        try
        {
            String titulos[] = {"DNI", "Nombre", "Apellidos", "Sueldo", "Fecha", "Matrícula"};
            m = new DefaultTableModel(null, titulos);
            
            ResultSet r = sentencia.executeQuery(consulta);
            
            String fila[] = new String[6];
            
            while(r.next())
            {
                fila[0] = r.getString("DNI");
                fila[1] = r.getString("Nombre");
                fila[2] = r.getString("Apellido");
                fila[3] = r.getString("Sueldo").replace(".", ",");
                fecha = r.getString("Fecha");
                fecha = fecha.substring(8, 10) + "/" + fecha.substring(5, 7) + "/" + fecha.substring(0, 4);
                fila[4] = fecha;
                fila[5] = r.getString("Matricula");
                
                m.addRow(fila);
            }
            
            tabla.setModel(m);
            tabla.setAutoResizeMode(AUTO_RESIZE_ALL_COLUMNS);
            
            hacerCalculos(r);
            dFilTrabajador.dispose();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al filtrar trabajadores " + e);
        }
    }//GEN-LAST:event_btnFAceptarActionPerformed

    private void btnFCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCancelarActionPerformed
        dFilTrabajador.dispose();
    }//GEN-LAST:event_btnFCancelarActionPerformed

    private void btnFVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFVerActionPerformed
        mostrarTrabajadores();
        dFilTrabajador.dispose();
    }//GEN-LAST:event_btnFVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFAceptar;
    private javax.swing.JButton btnFCancelar;
    private javax.swing.JButton btnFVer;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnMAceptar;
    private javax.swing.JButton btnMCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNAceptar;
    private javax.swing.JButton btnNCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cFecha;
    private javax.swing.JComboBox cSueldo;
    private javax.swing.JComboBox cbOrden;
    private javax.swing.JDialog dAddTrabajador;
    private javax.swing.JDialog dFilTrabajador;
    private javax.swing.JDialog dModTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAsc;
    private javax.swing.JRadioButton rbDesc;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtFAnio;
    private javax.swing.JTextField txtFApellidos;
    private javax.swing.JTextField txtFDia;
    private javax.swing.JTextField txtFDni;
    private javax.swing.JTextField txtFMatricula;
    private javax.swing.JTextField txtFMes;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFSueldo;
    private javax.swing.JTextField txtMAnio;
    private javax.swing.JTextField txtMApellidos;
    private javax.swing.JTextField txtMDia;
    private javax.swing.JTextField txtMDni;
    private javax.swing.JTextField txtMMatricula;
    private javax.swing.JTextField txtMMes;
    private javax.swing.JTextField txtMNombre;
    private javax.swing.JTextField txtMSueldo;
    private javax.swing.JTextField txtNAnio;
    private javax.swing.JTextField txtNApellidos;
    private javax.swing.JTextField txtNDia;
    private javax.swing.JTextField txtNDni;
    private javax.swing.JTextField txtNMatricula;
    private javax.swing.JTextField txtNMes;
    private javax.swing.JTextField txtNNombre;
    private javax.swing.JTextField txtNSueldo;
    private javax.swing.JTextField txtNtrab;
    private javax.swing.JTextField txtSmedio;
    // End of variables declaration//GEN-END:variables
}
