
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juanro
 */
public class Principal extends javax.swing.JFrame {

    static Vehiculo avis[] = new Vehiculo[8];
    static int numTurismos = 0, numTurAlquilados = 0;
    static int numCamiones = 0, numCamAlquilados = 0;
    private static boolean estado;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        llenar();
    }

    public static void llenar()
    {
        avis[0] = new Camion("AA-1111-A", 100);
        numCamiones++;
        avis[1] = new Turismo("BB-2222-B", 0.3);
        numTurismos++;
        avis[2] = new Turismo("CC-3333-C", 0.4);
        numTurismos++;
        avis[3] = new Camion("DD-4444-D", 120);
        numCamiones++;
        avis[4] = new Camion("EE-5555-A", 110);
        numCamiones++;
        avis[5] = new Turismo("FF-6666-B", 0.5);
        numTurismos++;
        avis[6] = new Turismo("GG-7777-C", 0.4);
        numTurismos++;
        avis[7] = new Camion("HH-8888-D", 120);
        numCamiones++;
    }
    
    public void cochesLibres() throws OcupadosException
    {
        if(Principal.numTurismos == Principal.numTurAlquilados)
        {
            throw new OcupadosException("No quedan coches para alquilar.");
        }
    }
    
    public void camionesLibres() throws OcupadosException
    {
        if(Principal.numCamiones == Principal.numCamAlquilados)
        {
            throw new OcupadosException("No quedan camiones para alquilar.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mListar = new javax.swing.JMenu();
        mAlquilar = new javax.swing.JMenu();
        miACoche = new javax.swing.JMenuItem();
        miACamion = new javax.swing.JMenuItem();
        mDevolver = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hack", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("ALQUILER DE VEHÍCULOS");

        mListar.setText("Listar");
        mListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mListarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mListar);

        mAlquilar.setText("Alquilar");

        miACoche.setText("Alquilar Coche");
        miACoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miACocheActionPerformed(evt);
            }
        });
        mAlquilar.add(miACoche);

        miACamion.setText("Alquilar Camión");
        miACamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miACamionActionPerformed(evt);
            }
        });
        mAlquilar.add(miACamion);

        jMenuBar1.add(mAlquilar);

        mDevolver.setText("Devolver");
        mDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDevolverMouseClicked(evt);
            }
        });
        jMenuBar1.add(mDevolver);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_mSalirMousePressed

    private void miACocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miACocheActionPerformed
        try
        {
            cochesLibres();
            miACoche.setEnabled(true);
            
            AlquilarCoche c = new AlquilarCoche();
            c.setVisible(true);
        }
        catch(OcupadosException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "OcupadosException", JOptionPane.WARNING_MESSAGE);
            miACoche.setEnabled(false);
        }
    }//GEN-LAST:event_miACocheActionPerformed

    private void mListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mListarMouseClicked
        new Listar().setVisible(true);
    }//GEN-LAST:event_mListarMouseClicked

    private void mDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDevolverMouseClicked
        new Devolver().setVisible(true);
    }//GEN-LAST:event_mDevolverMouseClicked

    private void miACamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miACamionActionPerformed
        try
        {
            camionesLibres();
            miACamion.setEnabled(true);
            
            AlquilarCamion c = new AlquilarCamion();
            c.setVisible(true);
        }
        catch(OcupadosException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "OcupadosException", JOptionPane.WARNING_MESSAGE);
            miACamion.setEnabled(false);
        }
    }//GEN-LAST:event_miACamionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mAlquilar;
    private javax.swing.JMenu mDevolver;
    private javax.swing.JMenu mListar;
    private javax.swing.JMenu mSalir;
    public static javax.swing.JMenuItem miACamion;
    public static javax.swing.JMenuItem miACoche;
    // End of variables declaration//GEN-END:variables
}
