
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class resistencias extends javax.swing.JFrame {
    String banda1, banda2, banda3, banda4;
    /**
     * Creates new form resistencias
     */
    public resistencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jPanelResi = new javax.swing.JPanel();
        txtBanda2 = new javax.swing.JTextField();
        txtBanda3 = new javax.swing.JTextField();
        txtBanda4 = new javax.swing.JTextField();
        txtBanda1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioPurpura1 = new javax.swing.JRadioButton();
        radioGris1 = new javax.swing.JRadioButton();
        radioBlanco1 = new javax.swing.JRadioButton();
        radioMarron1 = new javax.swing.JRadioButton();
        radioNegro1 = new javax.swing.JRadioButton();
        radioRojo1 = new javax.swing.JRadioButton();
        radioNaranja1 = new javax.swing.JRadioButton();
        radioAmarillo1 = new javax.swing.JRadioButton();
        radioVerde1 = new javax.swing.JRadioButton();
        radioAzul1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radioAzul2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioPurpura2 = new javax.swing.JRadioButton();
        radioGris2 = new javax.swing.JRadioButton();
        radioBlanco2 = new javax.swing.JRadioButton();
        radioMarron2 = new javax.swing.JRadioButton();
        radioNegro2 = new javax.swing.JRadioButton();
        radioRojo2 = new javax.swing.JRadioButton();
        radioNaranja2 = new javax.swing.JRadioButton();
        radioAmarillo2 = new javax.swing.JRadioButton();
        radioVerde2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        radioPurpura3 = new javax.swing.JRadioButton();
        radioGris3 = new javax.swing.JRadioButton();
        radioOro3 = new javax.swing.JRadioButton();
        radioBlanco3 = new javax.swing.JRadioButton();
        radioPlata3 = new javax.swing.JRadioButton();
        radioMarron3 = new javax.swing.JRadioButton();
        radioNegro3 = new javax.swing.JRadioButton();
        radioRojo3 = new javax.swing.JRadioButton();
        radioNaranja3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioAmarillo3 = new javax.swing.JRadioButton();
        radioVerde3 = new javax.swing.JRadioButton();
        radioAzul3 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radioPlata4 = new javax.swing.JRadioButton();
        radioNoCol4 = new javax.swing.JRadioButton();
        radioMarron4 = new javax.swing.JRadioButton();
        radioRojo4 = new javax.swing.JRadioButton();
        radioOro4 = new javax.swing.JRadioButton();
        radioVerde4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Calcular valor de una Resistencia");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jPanelResi.setBackground(new java.awt.Color(255, 255, 153));
        jPanelResi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelResiLayout = new javax.swing.GroupLayout(jPanelResi);
        jPanelResi.setLayout(jPanelResiLayout);
        jPanelResiLayout.setHorizontalGroup(
            jPanelResiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(txtBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(txtBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBanda4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanelResiLayout.setVerticalGroup(
            jPanelResiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanda2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtBanda3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtBanda4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtBanda1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Banda 1");

        radioPurpura1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioPurpura1);
        radioPurpura1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioPurpura1.setForeground(new java.awt.Color(153, 0, 153));
        radioPurpura1.setText("Púrpura");
        radioPurpura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPurpura1ActionPerformed(evt);
            }
        });

        radioGris1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioGris1);
        radioGris1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioGris1.setForeground(new java.awt.Color(102, 102, 102));
        radioGris1.setText("Gris");
        radioGris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGris1ActionPerformed(evt);
            }
        });

        radioBlanco1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioBlanco1);
        radioBlanco1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioBlanco1.setForeground(new java.awt.Color(255, 255, 255));
        radioBlanco1.setText("Blanco");
        radioBlanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlanco1ActionPerformed(evt);
            }
        });

        radioMarron1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioMarron1);
        radioMarron1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioMarron1.setForeground(new java.awt.Color(204, 153, 0));
        radioMarron1.setText("Marron");
        radioMarron1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMarron1ActionPerformed(evt);
            }
        });

        radioNegro1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioNegro1);
        radioNegro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNegro1.setText("Negro");
        radioNegro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNegro1ActionPerformed(evt);
            }
        });

        radioRojo1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioRojo1);
        radioRojo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioRojo1.setForeground(new java.awt.Color(255, 0, 51));
        radioRojo1.setText("Rojo");
        radioRojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRojo1ActionPerformed(evt);
            }
        });

        radioNaranja1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioNaranja1);
        radioNaranja1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNaranja1.setForeground(new java.awt.Color(255, 153, 51));
        radioNaranja1.setText("Naranja");
        radioNaranja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaranja1ActionPerformed(evt);
            }
        });

        radioAmarillo1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioAmarillo1);
        radioAmarillo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAmarillo1.setForeground(new java.awt.Color(255, 255, 0));
        radioAmarillo1.setText("Amarillo");
        radioAmarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAmarillo1ActionPerformed(evt);
            }
        });

        radioVerde1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioVerde1);
        radioVerde1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioVerde1.setForeground(new java.awt.Color(0, 255, 0));
        radioVerde1.setText("Verde");
        radioVerde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVerde1ActionPerformed(evt);
            }
        });

        radioAzul1.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup1.add(radioAzul1);
        radioAzul1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAzul1.setForeground(new java.awt.Color(0, 51, 255));
        radioAzul1.setText("Azul");
        radioAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAzul1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNegro1)
                    .addComponent(radioMarron1)
                    .addComponent(radioRojo1)
                    .addComponent(radioNaranja1)
                    .addComponent(radioAmarillo1)
                    .addComponent(radioVerde1)
                    .addComponent(radioAzul1)
                    .addComponent(radioPurpura1)
                    .addComponent(radioGris1)
                    .addComponent(radioBlanco1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNegro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMarron1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRojo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNaranja1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAmarillo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVerde1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAzul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPurpura1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGris1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBlanco1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        radioAzul2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioAzul2);
        radioAzul2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAzul2.setForeground(new java.awt.Color(0, 51, 255));
        radioAzul2.setText("Azul");
        radioAzul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAzul2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Banda 2");

        radioPurpura2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioPurpura2);
        radioPurpura2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioPurpura2.setForeground(new java.awt.Color(153, 0, 153));
        radioPurpura2.setText("Púrpura");
        radioPurpura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPurpura2ActionPerformed(evt);
            }
        });

        radioGris2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioGris2);
        radioGris2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioGris2.setForeground(new java.awt.Color(102, 102, 102));
        radioGris2.setText("Gris");
        radioGris2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGris2ActionPerformed(evt);
            }
        });

        radioBlanco2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioBlanco2);
        radioBlanco2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioBlanco2.setForeground(new java.awt.Color(255, 255, 255));
        radioBlanco2.setText("Blanco");
        radioBlanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlanco2ActionPerformed(evt);
            }
        });

        radioMarron2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioMarron2);
        radioMarron2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioMarron2.setForeground(new java.awt.Color(204, 153, 0));
        radioMarron2.setText("Marron");
        radioMarron2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMarron2ActionPerformed(evt);
            }
        });

        radioNegro2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioNegro2);
        radioNegro2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNegro2.setText("Negro");
        radioNegro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNegro2ActionPerformed(evt);
            }
        });

        radioRojo2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioRojo2);
        radioRojo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioRojo2.setForeground(new java.awt.Color(255, 0, 51));
        radioRojo2.setText("Rojo");
        radioRojo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRojo2ActionPerformed(evt);
            }
        });

        radioNaranja2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioNaranja2);
        radioNaranja2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNaranja2.setForeground(new java.awt.Color(255, 153, 51));
        radioNaranja2.setText("Naranja");
        radioNaranja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaranja2ActionPerformed(evt);
            }
        });

        radioAmarillo2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioAmarillo2);
        radioAmarillo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAmarillo2.setForeground(new java.awt.Color(255, 255, 0));
        radioAmarillo2.setText("Amarillo");
        radioAmarillo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAmarillo2ActionPerformed(evt);
            }
        });

        radioVerde2.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup2.add(radioVerde2);
        radioVerde2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioVerde2.setForeground(new java.awt.Color(0, 255, 0));
        radioVerde2.setText("Verde");
        radioVerde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVerde2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNegro2)
                    .addComponent(radioMarron2)
                    .addComponent(radioRojo2)
                    .addComponent(radioNaranja2)
                    .addComponent(radioAmarillo2)
                    .addComponent(radioVerde2)
                    .addComponent(radioAzul2)
                    .addComponent(radioPurpura2)
                    .addComponent(radioGris2)
                    .addComponent(radioBlanco2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNegro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMarron2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRojo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNaranja2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAmarillo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVerde2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAzul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPurpura2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGris2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBlanco2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        radioPurpura3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioPurpura3);
        radioPurpura3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioPurpura3.setForeground(new java.awt.Color(153, 0, 153));
        radioPurpura3.setText("Púrpura");
        radioPurpura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPurpura3ActionPerformed(evt);
            }
        });

        radioGris3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioGris3);
        radioGris3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioGris3.setForeground(new java.awt.Color(102, 102, 102));
        radioGris3.setText("Gris");
        radioGris3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGris3ActionPerformed(evt);
            }
        });

        radioOro3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioOro3);
        radioOro3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioOro3.setForeground(new java.awt.Color(204, 204, 0));
        radioOro3.setText("Oro");
        radioOro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOro3ActionPerformed(evt);
            }
        });

        radioBlanco3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioBlanco3);
        radioBlanco3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioBlanco3.setForeground(new java.awt.Color(255, 255, 255));
        radioBlanco3.setText("Blanco");
        radioBlanco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlanco3ActionPerformed(evt);
            }
        });

        radioPlata3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioPlata3);
        radioPlata3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioPlata3.setForeground(new java.awt.Color(204, 204, 204));
        radioPlata3.setText("Plata");
        radioPlata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPlata3ActionPerformed(evt);
            }
        });

        radioMarron3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioMarron3);
        radioMarron3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioMarron3.setForeground(new java.awt.Color(204, 153, 0));
        radioMarron3.setText("Marron");
        radioMarron3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMarron3ActionPerformed(evt);
            }
        });

        radioNegro3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioNegro3);
        radioNegro3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNegro3.setText("Negro");
        radioNegro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNegro3ActionPerformed(evt);
            }
        });

        radioRojo3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioRojo3);
        radioRojo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioRojo3.setForeground(new java.awt.Color(255, 0, 51));
        radioRojo3.setText("Rojo");
        radioRojo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRojo3ActionPerformed(evt);
            }
        });

        radioNaranja3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioNaranja3);
        radioNaranja3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNaranja3.setForeground(new java.awt.Color(255, 153, 51));
        radioNaranja3.setText("Naranja");
        radioNaranja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaranja3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Banda 3");

        radioAmarillo3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioAmarillo3);
        radioAmarillo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAmarillo3.setForeground(new java.awt.Color(255, 255, 0));
        radioAmarillo3.setText("Amarillo");
        radioAmarillo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAmarillo3ActionPerformed(evt);
            }
        });

        radioVerde3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioVerde3);
        radioVerde3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioVerde3.setForeground(new java.awt.Color(0, 255, 0));
        radioVerde3.setText("Verde");
        radioVerde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVerde3ActionPerformed(evt);
            }
        });

        radioAzul3.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup3.add(radioAzul3);
        radioAzul3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioAzul3.setForeground(new java.awt.Color(0, 51, 255));
        radioAzul3.setText("Azul");
        radioAzul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAzul3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radioGris3)
                        .addGap(26, 26, 26))
                    .addComponent(radioNegro3)
                    .addComponent(radioMarron3)
                    .addComponent(radioRojo3)
                    .addComponent(radioNaranja3)
                    .addComponent(radioAmarillo3)
                    .addComponent(radioVerde3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(radioOro3)
                            .addComponent(radioPlata3)
                            .addComponent(radioAzul3)
                            .addComponent(radioPurpura3)
                            .addComponent(radioBlanco3))
                        .addGap(2, 2, 2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNegro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMarron3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRojo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNaranja3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAmarillo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVerde3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAzul3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPurpura3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGris3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBlanco3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPlata3)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setText("Banda 4");

        radioPlata4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioPlata4);
        radioPlata4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioPlata4.setForeground(new java.awt.Color(204, 204, 204));
        radioPlata4.setText("Plata");
        radioPlata4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPlata4ActionPerformed(evt);
            }
        });

        radioNoCol4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioNoCol4);
        radioNoCol4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioNoCol4.setText("Sin Color");
        radioNoCol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoCol4ActionPerformed(evt);
            }
        });

        radioMarron4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioMarron4);
        radioMarron4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioMarron4.setForeground(new java.awt.Color(204, 153, 0));
        radioMarron4.setText("Marron");
        radioMarron4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMarron4ActionPerformed(evt);
            }
        });

        radioRojo4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioRojo4);
        radioRojo4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioRojo4.setForeground(new java.awt.Color(255, 0, 51));
        radioRojo4.setText("Rojo");
        radioRojo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRojo4ActionPerformed(evt);
            }
        });

        radioOro4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioOro4);
        radioOro4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioOro4.setForeground(new java.awt.Color(204, 204, 0));
        radioOro4.setText("Oro");
        radioOro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOro4ActionPerformed(evt);
            }
        });

        radioVerde4.setBackground(new java.awt.Color(0, 204, 153));
        buttonGroup4.add(radioVerde4);
        radioVerde4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioVerde4.setForeground(new java.awt.Color(0, 255, 0));
        radioVerde4.setText("Verde");
        radioVerde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVerde4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMarron4)
                        .addComponent(radioRojo4)
                        .addComponent(radioOro4)
                        .addComponent(radioVerde4)
                        .addComponent(radioPlata4)
                        .addComponent(radioNoCol4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMarron4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRojo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVerde4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOro4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPlata4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNoCol4)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelResi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(btnCalcular)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanelResi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMarron1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMarron1ActionPerformed
        banda1 = "1";
        txtBanda1.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_radioMarron1ActionPerformed

    private void radioNegro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNegro1ActionPerformed
        banda1 = "0";
        txtBanda1.setBackground(Color.BLACK);
    }//GEN-LAST:event_radioNegro1ActionPerformed

    private void radioRojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRojo1ActionPerformed
        banda1 = "2";
        txtBanda1.setBackground(Color.RED);
    }//GEN-LAST:event_radioRojo1ActionPerformed

    private void radioNaranja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaranja1ActionPerformed
        banda1 = "3";
        txtBanda1.setBackground(Color.ORANGE);
    }//GEN-LAST:event_radioNaranja1ActionPerformed

    private void radioAmarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAmarillo1ActionPerformed
        banda1 = "4";
        txtBanda1.setBackground(Color.YELLOW);
    }//GEN-LAST:event_radioAmarillo1ActionPerformed

    private void radioVerde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVerde1ActionPerformed
        banda1 = "5";
        txtBanda1.setBackground(Color.GREEN);
    }//GEN-LAST:event_radioVerde1ActionPerformed

    private void radioAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAzul1ActionPerformed
        banda1 = "6";
        txtBanda1.setBackground(Color.BLUE);
    }//GEN-LAST:event_radioAzul1ActionPerformed

    private void radioPurpura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPurpura1ActionPerformed
        banda1 = "7";
        txtBanda1.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_radioPurpura1ActionPerformed

    private void radioGris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGris1ActionPerformed
        banda1 = "8";
        txtBanda1.setBackground(Color.GRAY);
    }//GEN-LAST:event_radioGris1ActionPerformed

    private void radioBlanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlanco1ActionPerformed
        banda1 = "9";
        txtBanda1.setBackground(Color.WHITE);
    }//GEN-LAST:event_radioBlanco1ActionPerformed

    private void radioPurpura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPurpura2ActionPerformed
        banda2 = "7";
        txtBanda2.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_radioPurpura2ActionPerformed

    private void radioGris2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGris2ActionPerformed
        banda2 = "8";
        txtBanda2.setBackground(Color.GRAY);
    }//GEN-LAST:event_radioGris2ActionPerformed

    private void radioBlanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlanco2ActionPerformed
        banda2 = "9";
        txtBanda2.setBackground(Color.WHITE);
    }//GEN-LAST:event_radioBlanco2ActionPerformed

    private void radioMarron2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMarron2ActionPerformed
        banda2 = "1";
        txtBanda2.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_radioMarron2ActionPerformed

    private void radioNegro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNegro2ActionPerformed
       banda2 = "0";
       txtBanda2.setBackground(Color.BLACK);
    }//GEN-LAST:event_radioNegro2ActionPerformed

    private void radioRojo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRojo2ActionPerformed
        banda2 = "2";
        txtBanda2.setBackground(Color.RED);
    }//GEN-LAST:event_radioRojo2ActionPerformed

    private void radioNaranja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaranja2ActionPerformed
        banda2 = "3";
        txtBanda2.setBackground(Color.ORANGE);
    }//GEN-LAST:event_radioNaranja2ActionPerformed

    private void radioAmarillo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAmarillo2ActionPerformed
        banda2 = "4";
        txtBanda2.setBackground(Color.YELLOW);
    }//GEN-LAST:event_radioAmarillo2ActionPerformed

    private void radioVerde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVerde2ActionPerformed
        banda2 = "5";
        txtBanda2.setBackground(Color.GREEN);
    }//GEN-LAST:event_radioVerde2ActionPerformed

    private void radioAzul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAzul2ActionPerformed
        banda2 = "6";
        txtBanda2.setBackground(Color.BLUE);
    }//GEN-LAST:event_radioAzul2ActionPerformed

    private void radioPurpura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPurpura3ActionPerformed
        banda3 = "10000000";
        txtBanda3.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_radioPurpura3ActionPerformed

    private void radioGris3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGris3ActionPerformed
        banda3 = "100000000";
        txtBanda3.setBackground(Color.GRAY);
    }//GEN-LAST:event_radioGris3ActionPerformed

    private void radioBlanco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlanco3ActionPerformed
        banda3 = "1000000000";
        txtBanda3.setBackground(Color.WHITE);
    }//GEN-LAST:event_radioBlanco3ActionPerformed

    private void radioMarron3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMarron3ActionPerformed
        banda3 = "10";
        txtBanda3.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_radioMarron3ActionPerformed

    private void radioNegro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNegro3ActionPerformed
        banda3 = "0";
        txtBanda3.setBackground(Color.black);
    }//GEN-LAST:event_radioNegro3ActionPerformed

    private void radioRojo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRojo3ActionPerformed
        banda3 = "100";
        txtBanda3.setBackground(Color.RED);
    }//GEN-LAST:event_radioRojo3ActionPerformed

    private void radioNaranja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaranja3ActionPerformed
        banda3 = "1000";
        txtBanda3.setBackground(Color.orange);
    }//GEN-LAST:event_radioNaranja3ActionPerformed

    private void radioAmarillo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAmarillo3ActionPerformed
        banda3 = "1000";
        txtBanda3.setBackground(Color.YELLOW);
    }//GEN-LAST:event_radioAmarillo3ActionPerformed

    private void radioVerde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVerde3ActionPerformed
        banda3 = "10000";
        txtBanda3.setBackground(Color.GREEN);
    }//GEN-LAST:event_radioVerde3ActionPerformed

    private void radioAzul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAzul3ActionPerformed
        banda3 = "100000";
        txtBanda3.setBackground(Color.RED);
    }//GEN-LAST:event_radioAzul3ActionPerformed

    private void radioPlata4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPlata4ActionPerformed
        banda3 = "0.01";
        txtBanda4.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_radioPlata4ActionPerformed

    private void radioNoCol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoCol4ActionPerformed
        banda4 = "20";
        txtBanda4.setBackground(Color.WHITE);
    }//GEN-LAST:event_radioNoCol4ActionPerformed

    private void radioMarron4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMarron4ActionPerformed
        banda4 = "1";
        txtBanda4.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_radioMarron4ActionPerformed

    private void radioRojo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRojo4ActionPerformed
        banda4 = "2";
        txtBanda4.setBackground(Color.red);
    }//GEN-LAST:event_radioRojo4ActionPerformed

    private void radioOro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOro4ActionPerformed
        banda4 = "5";
        txtBanda4.setBackground(new java.awt.Color(204, 204, 0));
    }//GEN-LAST:event_radioOro4ActionPerformed

    private void radioVerde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVerde4ActionPerformed
        banda4 = "0.5";
        txtBanda4.setBackground(Color.GREEN);
    }//GEN-LAST:event_radioVerde4ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double resistencia, ohmios, vmax, vmin;
        boolean sw = true;

        if(banda1 == null)
        {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento de la banda 1", "Error", JOptionPane.WARNING_MESSAGE);
            sw = false;
        }

        if(banda2 == null)
        {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento de la banda 2", "Error", JOptionPane.WARNING_MESSAGE);
            sw = false;
        }

        if(banda3 == null)
        {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento de la banda 3", "Error", JOptionPane.WARNING_MESSAGE);
            sw = false;
        }

        if(banda4 == null)
        {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento de la banda 4", "Error", JOptionPane.WARNING_MESSAGE);
            sw = false;
        }

        if(sw)
        {
            resistencia = Double.parseDouble(banda1 + banda2) * Double.parseDouble(banda3);
            ohmios = (resistencia * Double.parseDouble(banda4)) / 100;
            vmax = resistencia + ohmios;
            vmin = resistencia - ohmios;

            JOptionPane.showMessageDialog(null, "VN= " + resistencia + " Ohmios\n"
                + "T %= " + banda4 + "%\n"
                + "T Ohmios= " + ohmios + " Ohmios\n"
                + "V Max= " + vmax + " Ohmios\n"
                + "V min= " + vmin + " Ohmios\n","Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void radioOro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOro3ActionPerformed
        banda3 = "0.1";
        txtBanda3.setBackground(new java.awt.Color(204, 204, 0));
    }//GEN-LAST:event_radioOro3ActionPerformed

    private void radioPlata3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPlata3ActionPerformed
        banda3 = "0.01";
        txtBanda3.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_radioPlata3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resistencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelResi;
    private javax.swing.JRadioButton radioAmarillo1;
    private javax.swing.JRadioButton radioAmarillo2;
    private javax.swing.JRadioButton radioAmarillo3;
    private javax.swing.JRadioButton radioAzul1;
    private javax.swing.JRadioButton radioAzul2;
    private javax.swing.JRadioButton radioAzul3;
    private javax.swing.JRadioButton radioBlanco1;
    private javax.swing.JRadioButton radioBlanco2;
    private javax.swing.JRadioButton radioBlanco3;
    private javax.swing.JRadioButton radioGris1;
    private javax.swing.JRadioButton radioGris2;
    private javax.swing.JRadioButton radioGris3;
    private javax.swing.JRadioButton radioMarron1;
    private javax.swing.JRadioButton radioMarron2;
    private javax.swing.JRadioButton radioMarron3;
    private javax.swing.JRadioButton radioMarron4;
    private javax.swing.JRadioButton radioNaranja1;
    private javax.swing.JRadioButton radioNaranja2;
    private javax.swing.JRadioButton radioNaranja3;
    private javax.swing.JRadioButton radioNegro1;
    private javax.swing.JRadioButton radioNegro2;
    private javax.swing.JRadioButton radioNegro3;
    private javax.swing.JRadioButton radioNoCol4;
    private javax.swing.JRadioButton radioOro3;
    private javax.swing.JRadioButton radioOro4;
    private javax.swing.JRadioButton radioPlata3;
    private javax.swing.JRadioButton radioPlata4;
    private javax.swing.JRadioButton radioPurpura1;
    private javax.swing.JRadioButton radioPurpura2;
    private javax.swing.JRadioButton radioPurpura3;
    private javax.swing.JRadioButton radioRojo1;
    private javax.swing.JRadioButton radioRojo2;
    private javax.swing.JRadioButton radioRojo3;
    private javax.swing.JRadioButton radioRojo4;
    private javax.swing.JRadioButton radioVerde1;
    private javax.swing.JRadioButton radioVerde2;
    private javax.swing.JRadioButton radioVerde3;
    private javax.swing.JRadioButton radioVerde4;
    private javax.swing.JTextField txtBanda1;
    private javax.swing.JTextField txtBanda2;
    private javax.swing.JTextField txtBanda3;
    private javax.swing.JTextField txtBanda4;
    // End of variables declaration//GEN-END:variables
}
