/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

/**
 *
 * @author Juanro49
 */
public class Principal extends javax.swing.JFrame
{

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        mUsu = new javax.swing.JMenu();
        mAltaU = new javax.swing.JMenuItem();
        mBajaU = new javax.swing.JMenuItem();
        mModificarU = new javax.swing.JMenuItem();
        mListadoU = new javax.swing.JMenuItem();
        mNoti = new javax.swing.JMenu();
        mAltaN = new javax.swing.JMenuItem();
        mBajaN = new javax.swing.JMenuItem();
        mModN = new javax.swing.JMenuItem();
        mListaN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mUsu.setText("Usuarios");

        mAltaU.setText("Alta");
        mAltaU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mAltaUActionPerformed(evt);
            }
        });
        mUsu.add(mAltaU);

        mBajaU.setText("Baja");
        mBajaU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mBajaUActionPerformed(evt);
            }
        });
        mUsu.add(mBajaU);

        mModificarU.setText("Modificar");
        mModificarU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mModificarUActionPerformed(evt);
            }
        });
        mUsu.add(mModificarU);

        mListadoU.setText("Listado");
        mListadoU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mListadoUActionPerformed(evt);
            }
        });
        mUsu.add(mListadoU);

        jMenuBar1.add(mUsu);

        mNoti.setText("Noticias");

        mAltaN.setText("Alta");
        mAltaN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mAltaNActionPerformed(evt);
            }
        });
        mNoti.add(mAltaN);

        mBajaN.setText("Baja");
        mNoti.add(mBajaN);

        mModN.setText("Modificar");
        mNoti.add(mModN);

        mListaN.setText("Listar");
        mListaN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mListaNActionPerformed(evt);
            }
        });
        mNoti.add(mListaN);

        jMenuBar1.add(mNoti);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAltaUActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mAltaUActionPerformed
    {//GEN-HEADEREND:event_mAltaUActionPerformed
        vista.AltaUsuarios user = new vista.AltaUsuarios();
        user.setVisible(true);
    }//GEN-LAST:event_mAltaUActionPerformed

    private void mListadoUActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mListadoUActionPerformed
    {//GEN-HEADEREND:event_mListadoUActionPerformed
        vista.ListaUsuarios user = new vista.ListaUsuarios();
        user.setVisible(true);
    }//GEN-LAST:event_mListadoUActionPerformed

    private void mModificarUActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mModificarUActionPerformed
    {//GEN-HEADEREND:event_mModificarUActionPerformed
        vista.ModificarUsuario user = new vista.ModificarUsuario();
        user.setVisible(true);
    }//GEN-LAST:event_mModificarUActionPerformed

    private void mBajaUActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mBajaUActionPerformed
    {//GEN-HEADEREND:event_mBajaUActionPerformed
        vista.BajaUsuarios user = new vista.BajaUsuarios();
        user.setVisible(true);
    }//GEN-LAST:event_mBajaUActionPerformed

    private void mAltaNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mAltaNActionPerformed
    {//GEN-HEADEREND:event_mAltaNActionPerformed
        new AltaNoticias().setVisible(true);
    }//GEN-LAST:event_mAltaNActionPerformed

    private void mListaNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mListaNActionPerformed
    {//GEN-HEADEREND:event_mListaNActionPerformed
        new ListaNoticias().setVisible(true);
    }//GEN-LAST:event_mListaNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAltaN;
    private javax.swing.JMenuItem mAltaU;
    private javax.swing.JMenuItem mBajaN;
    private javax.swing.JMenuItem mBajaU;
    private javax.swing.JMenuItem mListaN;
    private javax.swing.JMenuItem mListadoU;
    private javax.swing.JMenuItem mModN;
    private javax.swing.JMenuItem mModificarU;
    private javax.swing.JMenu mNoti;
    private javax.swing.JMenu mUsu;
    // End of variables declaration//GEN-END:variables
}
