
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Grafica extends javax.swing.JFrame {

    static ArrayList <Libro> Libros = new ArrayList();
    static ArrayList <Periodico> Periodicos = new ArrayList();

    /**
     * Creates new form Gracica
     */
    public Grafica() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLibreria = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mLibros = new javax.swing.JMenu();
        elemAltasL = new javax.swing.JMenuItem();
        elemMostrarL = new javax.swing.JMenuItem();
        mPeriodicos = new javax.swing.JMenu();
        elemAltasP = new javax.swing.JMenuItem();
        elemMostrarP = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtLibreria.setEditable(false);
        txtLibreria.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        txtLibreria.setForeground(new java.awt.Color(255, 51, 51));
        txtLibreria.setText("Mi Librería");
        txtLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibreriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(txtLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(txtLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        mLibros.setText("Libros");

        elemAltasL.setText("Altas");
        elemAltasL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemAltasLMouseClicked(evt);
            }
        });
        elemAltasL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemAltasLActionPerformed(evt);
            }
        });
        mLibros.add(elemAltasL);

        elemMostrarL.setText("Mostrar");
        elemMostrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemMostrarLActionPerformed(evt);
            }
        });
        mLibros.add(elemMostrarL);

        jMenuBar1.add(mLibros);

        mPeriodicos.setText("Periódicos");

        elemAltasP.setText("Altas");
        elemAltasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemAltasPActionPerformed(evt);
            }
        });
        mPeriodicos.add(elemAltasP);

        elemMostrarP.setText("Mostrar");
        elemMostrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemMostrarPActionPerformed(evt);
            }
        });
        mPeriodicos.add(elemMostrarP);

        jMenuBar1.add(mPeriodicos);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibreriaActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        
    }//GEN-LAST:event_mSalirActionPerformed

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mSalirMouseClicked

    private void elemAltasLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemAltasLMouseClicked
        
    }//GEN-LAST:event_elemAltasLMouseClicked

    private void elemAltasLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemAltasLActionPerformed
        new AltaLibro().setVisible(true);
    }//GEN-LAST:event_elemAltasLActionPerformed

    private void elemMostrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemMostrarLActionPerformed
        new MostrarLibro().setVisible(true);
    }//GEN-LAST:event_elemMostrarLActionPerformed

    private void elemAltasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemAltasPActionPerformed
        new AltaPeriodico().setVisible(true);
    }//GEN-LAST:event_elemAltasPActionPerformed

    private void elemMostrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemMostrarPActionPerformed
        new MostrarPeriodico().setVisible(true);
    }//GEN-LAST:event_elemMostrarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem elemAltasL;
    private javax.swing.JMenuItem elemAltasP;
    private javax.swing.JMenuItem elemMostrarL;
    private javax.swing.JMenuItem elemMostrarP;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mLibros;
    private javax.swing.JMenu mPeriodicos;
    private javax.swing.JMenu mSalir;
    private javax.swing.JTextField txtLibreria;
    // End of variables declaration//GEN-END:variables
}
