/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Grafica extends javax.swing.JFrame {
    public static String fichero;
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miCrear = new javax.swing.JMenuItem();
        miMostrar = new javax.swing.JMenuItem();
        mOperaciones = new javax.swing.JMenu();
        miCVocales = new javax.swing.JMenuItem();
        miCPalabras = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mArchivo.setText("Archivo");

        miCrear.setText("Crear");
        miCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearActionPerformed(evt);
            }
        });
        mArchivo.add(miCrear);

        miMostrar.setText("Mostrar");
        miMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMostrarActionPerformed(evt);
            }
        });
        mArchivo.add(miMostrar);

        jMenuBar1.add(mArchivo);

        mOperaciones.setText("Opetaciones Archivos");

        miCVocales.setText("Contar Vocales");
        miCVocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCVocalesActionPerformed(evt);
            }
        });
        mOperaciones.add(miCVocales);

        miCPalabras.setText("Contar Palabras");
        miCPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCPalabrasActionPerformed(evt);
            }
        });
        mOperaciones.add(miCPalabras);

        jMenuBar1.add(mOperaciones);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_mSalirMouseClicked

    private void miCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearActionPerformed
        new Crear().setVisible(true);
    }//GEN-LAST:event_miCrearActionPerformed

    private void miMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMostrarActionPerformed
        new Mostrar().setVisible(true);
    }//GEN-LAST:event_miMostrarActionPerformed

    private void miCPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCPalabrasActionPerformed
        new ContarPalabras().setVisible(true);
    }//GEN-LAST:event_miCPalabrasActionPerformed

    private void miCVocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCVocalesActionPerformed
        new ContarVocales().setVisible(true);
    }//GEN-LAST:event_miCVocalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mOperaciones;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem miCPalabras;
    private javax.swing.JMenuItem miCVocales;
    private javax.swing.JMenuItem miCrear;
    private javax.swing.JMenuItem miMostrar;
    // End of variables declaration//GEN-END:variables
}
