
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class AppFigura extends javax.swing.JFrame {

    ArrayList <Figura> listaFiguras = new ArrayList();
    /**
     * Creates new form AppFigura
     */
    public AppFigura() {
        initComponents();
        panFigura.setVisible(false);
        panCirculo.setVisible(false);
        panRect.setVisible(false);
        panMostrar.setVisible(false);
        btnOk.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTamL = new javax.swing.JLabel();
        txtTamL = new javax.swing.JTextField();
        panMenu = new javax.swing.JPanel();
        btnAddF = new javax.swing.JButton();
        btnMostrarF = new javax.swing.JButton();
        panFigura = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiguras = new javax.swing.JList();
        btnSeguir = new javax.swing.JButton();
        panCirculo = new javax.swing.JPanel();
        labPosc = new javax.swing.JLabel();
        labXc = new javax.swing.JLabel();
        labYc = new javax.swing.JLabel();
        txtXc = new javax.swing.JTextField();
        txtYc = new javax.swing.JTextField();
        labRadio = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        panRect = new javax.swing.JPanel();
        labPosr = new javax.swing.JLabel();
        labXr = new javax.swing.JLabel();
        labYr = new javax.swing.JLabel();
        txtXr = new javax.swing.JTextField();
        txtYr = new javax.swing.JTextField();
        labBase = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        labAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        panMostrar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTamL.setText("Tamaño Lista Figuras:");

        txtTamL.setEditable(false);
        txtTamL.setBackground(new java.awt.Color(204, 204, 204));
        txtTamL.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        panMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddF.setText("Añadir Figura");
        btnAddF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFActionPerformed(evt);
            }
        });

        btnMostrarF.setText("Mostrar Figuras");
        btnMostrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddF)
                    .addComponent(btnMostrarF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAddF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnMostrarF)
                .addGap(69, 69, 69))
        );

        panFigura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listFiguras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Círculo", "Rectángulo" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listFiguras);

        btnSeguir.setText("Seguir");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFiguraLayout = new javax.swing.GroupLayout(panFigura);
        panFigura.setLayout(panFiguraLayout);
        panFiguraLayout.setHorizontalGroup(
            panFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFiguraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeguir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panFiguraLayout.setVerticalGroup(
            panFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFiguraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeguir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panCirculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labPosc.setText("Posición Centro:");

        labXc.setText("Coordenada X:");

        labYc.setText("Coordenada Y:");

        labRadio.setText("Radio:");

        javax.swing.GroupLayout panCirculoLayout = new javax.swing.GroupLayout(panCirculo);
        panCirculo.setLayout(panCirculoLayout);
        panCirculoLayout.setHorizontalGroup(
            panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCirculoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCirculoLayout.createSequentialGroup()
                                .addComponent(labYc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYc))
                            .addGroup(panCirculoLayout.createSequentialGroup()
                                .addComponent(labXc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXc))))
                    .addGroup(panCirculoLayout.createSequentialGroup()
                        .addComponent(labPosc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panCirculoLayout.createSequentialGroup()
                        .addComponent(labRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRadio)))
                .addContainerGap())
        );
        panCirculoLayout.setVerticalGroup(
            panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labPosc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labXc)
                    .addComponent(txtXc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labYc)
                    .addComponent(txtYc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labRadio)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        panRect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labPosr.setText("Posición Centro:");

        labXr.setText("Coordenada X:");

        labYr.setText("Coordenada Y:");

        labBase.setText("Base:");

        labAltura.setText("Altura:");

        javax.swing.GroupLayout panRectLayout = new javax.swing.GroupLayout(panRect);
        panRect.setLayout(panRectLayout);
        panRectLayout.setHorizontalGroup(
            panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRectLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panRectLayout.createSequentialGroup()
                                .addComponent(labYr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYr, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                            .addGroup(panRectLayout.createSequentialGroup()
                                .addComponent(labXr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXr))))
                    .addGroup(panRectLayout.createSequentialGroup()
                        .addComponent(labPosr)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panRectLayout.createSequentialGroup()
                        .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAltura)
                            .addComponent(labBase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBase)
                            .addComponent(txtAltura))))
                .addContainerGap())
        );
        panRectLayout.setVerticalGroup(
            panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labPosr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labXr)
                    .addComponent(txtXr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labYr)
                    .addComponent(txtYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labBase)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane2.setViewportView(txtMostrar);

        javax.swing.GroupLayout panMostrarLayout = new javax.swing.GroupLayout(panMostrar);
        panMostrar.setLayout(panMostrarLayout);
        panMostrarLayout.setHorizontalGroup(
            panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panMostrarLayout.setVerticalGroup(
            panMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(labTamL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panRect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTamL)
                    .addComponent(txtTamL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFActionPerformed
        panFigura.setVisible(true);
        panMostrar.setVisible(false);
    }//GEN-LAST:event_btnAddFActionPerformed

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
        if(listFiguras.getSelectedIndex() == 0)
        {
            panCirculo.setVisible(true);
            panRect.setVisible(false);
        }
        
        if(listFiguras.getSelectedIndex() == 1)
        {
            panRect.setVisible(true);
            panCirculo.setVisible(false);
        }
        
        btnOk.setVisible(true);
    }//GEN-LAST:event_btnSeguirActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int[] pos = new int[2];
        double[] lado = new double[2];
        double radio = 0;
        boolean b = true;
        String cad = "";
        
        if(panCirculo.isVisible())
        {
            if(txtXc.getText().isEmpty())
            {
                cad += "Introduce X\n";
                b = false;
            }
            
            if(txtYc.getText().isEmpty())
            {
                cad += "Introduce Y\n";
                b = false;
            }
            
            if(txtRadio.getText().isEmpty())
            {
                cad += "Introduce el Radio\n";
                b = false;
            }
            
            if(b == false)
            {
                JOptionPane.showMessageDialog(null, cad, "Error", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                try
                {
                    pos[0] = Integer.parseInt(txtXc.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "X no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
                
                try
                {
                    pos[1] = Integer.parseInt(txtYc.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Y no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
                
                try
                {
                    radio = Float.parseFloat(txtRadio.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Radio no válido", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
            }
            
            if(b)
            {
                Figura circulo = new Circulo(radio, pos);
                listaFiguras.add(circulo);
                JOptionPane.showMessageDialog(null, "Figura añadida", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                
                btnOk.setVisible(false);
                panCirculo.setVisible(false);
                panFigura.setVisible(false);
                
                txtTamL.setText(String.valueOf(listaFiguras.size()));
            }
        }
        
        if(panRect.isVisible())
        {
            if(txtXr.getText().isEmpty())
            {
                cad += "Introduce X\n";
                b = false;
            }
            
            if(txtYr.getText().isEmpty())
            {
                cad += "Introduce Y\n";
                b = false;
            }
            
            if(txtBase.getText().isEmpty())
            {
                cad += "Introduce la base\n";
                b = false;
            }
            
            if(txtAltura.getText().isEmpty())
            {
                cad += "Introduce la altura\n";
                b = false;
            }
            
            if(b == false)
            {
                JOptionPane.showMessageDialog(null, cad, "Error", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                try
                {
                    pos[0] = Integer.parseInt(txtXr.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "X no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
                
                try
                {
                    pos[1] = Integer.parseInt(txtYr.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Y no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
                
                try
                {
                    lado[0] = Float.parseFloat(txtBase.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Base no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
                
                try
                {
                    lado[1] = Float.parseFloat(txtAltura.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Altura no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    b = false;
                }
            }
            
            if(b)
            {
                Figura rectangulo = new Rectangulo(lado, pos);
                listaFiguras.add(rectangulo);
                JOptionPane.showMessageDialog(null, "Figura añadida", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                
                btnOk.setVisible(false);
                panRect.setVisible(false);
                panFigura.setVisible(false);
                
                txtTamL.setText(String.valueOf(listaFiguras.size()));
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnMostrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFActionPerformed
        panFigura.setVisible(false);
        
        for (int i = 0; i < listaFiguras.size(); i++)
        {
            txtMostrar.append(listaFiguras.get(i).toString());
        }
        
        panMostrar.setVisible(true);
    }//GEN-LAST:event_btnMostrarFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFigura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddF;
    private javax.swing.JButton btnMostrarF;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSeguir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labAltura;
    private javax.swing.JLabel labBase;
    private javax.swing.JLabel labPosc;
    private javax.swing.JLabel labPosr;
    private javax.swing.JLabel labRadio;
    private javax.swing.JLabel labTamL;
    private javax.swing.JLabel labXc;
    private javax.swing.JLabel labXr;
    private javax.swing.JLabel labYc;
    private javax.swing.JLabel labYr;
    private javax.swing.JList listFiguras;
    private javax.swing.JPanel panCirculo;
    private javax.swing.JPanel panFigura;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panMostrar;
    private javax.swing.JPanel panRect;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtTamL;
    private javax.swing.JTextField txtXc;
    private javax.swing.JTextField txtXr;
    private javax.swing.JTextField txtYc;
    private javax.swing.JTextField txtYr;
    // End of variables declaration//GEN-END:variables
}
